spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/test
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : select 1
    test-on-borrow : false
    test-while-idle : true
    time-between-eviction-runs-millis : 18800
    jdbc-interceptors : ConnectionState;SlowQueryReport(threshold=0)
  
  data :
    neo4j :
      uri : http://localhost:7474
      username : neo4j
      password : 123456
      session :
        scope : session
      
security :
  user :
    name : admin
    password : admin



